<?php
/** @var Project\PublicityBannerModule\Block\PublicityBanner $block */
/** @var $escaper Magento\Framework\Escaper */
?>
<?php
$imageUrl = $block->getImageUrl();
$publicityIsActive = $block->getPublicityIsActive();
?>
<?php if($publicityIsActive): ?>
<div class="publicity_banner">
<span class="label"><<?= $escaper->escapeHtmlAttr($block->getLabel()) ?></span>
<span class="image">
    <img src="<?= $escaper->escapeUrl($imageUrl) ?>"
         alt="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>"
         id="product-gallery-image"
         class="image"/>
    </span>
<span class="description"><?= $escaper->escapeHtmlAttr($block->getDescription()) ?></span>
</div>
<?php endif; ?>
